### ISSUE TITLE
Missing features tracking

### ISSUE THREAD

**Issue by olehmisar** [noir-lang/zk-regex#6]
This issue is migrated from https://github.com/olehmisar/zk-regex/issues/4

Add noir support to zk-regex.

To test:
1. `git clone https://github.com/olehmisar/zk-regex.git`
2. `git checkout noir`
3. `cd packages/compiler`
4. `cargo run --bin zk-regex raw -r "m[10]-[ab]+;" --noir-file-path my_file.nr`

Missing features:
- [x] end anchor support https://github.com/noir-lang/zk-regex/issues/4
- [ ] start anchor support https://github.com/noir-lang/zk-regex/pull/1
- [ ] `gen_substrs` 
  - [ ] https://github.com/noir-lang/zk-regex/pull/2 
  - [ ] https://github.com/noir-lang/zk-regex/issues/5
- [ ] I did not test `^` and `$` and overall, not a lot of testing was conducted
- [ ] lookup table optimization
- [ ] tests
